// All icon-importing logic for SkillsSection, sourced from react-icons/si
// (plus one react-icons/di icon — AWS has no Simple Icons mark). Each entry
// in SKILL_ICONS maps a `skill.icon` key from portfolio-data.json to the
// react-icons component that renders it and its brand color.

import {
  SiPython,
  SiJavascript,
  SiReact,
  SiVite,
  SiTailwindcss,
  SiReactrouter,
  SiDjango,
  SiPostgresql,
  SiRedis,
  SiDocker,
  SiGithubactions,
  SiNginx,
  SiLinux,
  SiSupabase,
  SiVercel,
  SiCypress,
  SiPytest,
  SiJest,
  SiGit,
  SiAxios,
  SiStripe,
  SiClaude,
  SiGooglegemini,
  SiBootstrap,
  SiHtml5,
  SiCss,
  SiPytorch,
  SiScikitlearn,
  SiPandas,
  SiNumpy,
  SiGithubpages,
  SiPostman,
  SiFigma,
  SiGithub,
} from 'react-icons/si'
import { DiAws } from 'react-icons/di'

export const SKILL_ICONS = {
  python: { Icon: SiPython, color: '#3776AB' },
  javascript: { Icon: SiJavascript, color: '#F7DF1E' },
  react: { Icon: SiReact, color: '#61DAFB' },
  vite: { Icon: SiVite, color: '#646CFF' },
  tailwind: { Icon: SiTailwindcss, color: '#38BDF8' },
  reactrouter: { Icon: SiReactrouter, color: '#CA4245' },
  django: { Icon: SiDjango, color: '#092E20' },
  postgresql: { Icon: SiPostgresql, color: '#4169E1' },
  redis: { Icon: SiRedis, color: '#DC382D' },
  docker: { Icon: SiDocker, color: '#2496ED' },
  githubactions: { Icon: SiGithubactions, color: '#2088FF' },
  aws: { Icon: DiAws, color: '#FF9900' },
  nginx: { Icon: SiNginx, color: '#009639' },
  linux: { Icon: SiLinux, color: '#FCC624' },
  supabase: { Icon: SiSupabase, color: '#3FCF8E' },
  vercel: { Icon: SiVercel, color: '#000000' },
  cypress: { Icon: SiCypress, color: '#17202C' },
  pytest: { Icon: SiPytest, color: '#0A9EDC' },
  jest: { Icon: SiJest, color: '#C21325' },
  git: { Icon: SiGit, color: '#F05032' },
  axios: { Icon: SiAxios, color: '#5A29E4' },
  stripe: { Icon: SiStripe, color: '#635BFF' },
  claudecode: { Icon: SiClaude, color: '#D97757' },
  gemini: { Icon: SiGooglegemini, color: '#8E75B2' },
  bootstrap: { Icon: SiBootstrap, color: '#7952B3' },
  html: { Icon: SiHtml5, color: '#E34F26' },
  css: { Icon: SiCss, color: '#663399' },
  pytorch: { Icon: SiPytorch, color: '#EE4C2C' },
  scikitlearn: { Icon: SiScikitlearn, color: '#F7931E' },
  pandas: { Icon: SiPandas, color: '#150458' },
  numpy: { Icon: SiNumpy, color: '#013243' },
  githubpages: { Icon: SiGithubpages, color: '#222222' },
  postman: { Icon: SiPostman, color: '#FF6C37' },
  figma: { Icon: SiFigma, color: '#F24E1E' },
  github: { Icon: SiGithub, color: '#181717' },
}

// Skills with no distinct brand mark (a practice/spec rather than a product,
// or a logo that doesn't visually stand on its own) render as a text badge.
export const FALLBACK_LABELS = {
  drf: 'DRF',
}
